// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
char findTheDifference(string s, string t) {
    // Initialize an unordered_map to store character counts
    unordered_map<char, int> charCount;

    // Count characters in string s
    for (char c : s) {
        charCount[c]++;
    }

    // Count characters in string t and find the extra character
    for (char c : t) {
        if (charCount.find(c) != charCount.end() && charCount[c] > 0) {
            charCount[c]--;
        } else {
            return c;
        }
    }

    return ' '; // Return a default value if no extra character is found (this can be adjusted based on your specific requirements)
}
